name: Daily Netlify Deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build hook
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
