name: Daily Netlify Deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Node CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build website
        run: yarn && yarn build
        env:
            GOODREADS_API_KEY: ${{ secrets.GOODREADS_API_KEY }}
      - name: Upload to netlify
        uses: netlify/actions/cli@master
        with:
            args: deploy --prod
        env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

